# Generated by Django 3.2.5 on 2021-07-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
