# Generated by Django 3.2.5 on 2021-08-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_ingredientes_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='id_factura',
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.factura')),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='factura',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='caja.factura', null=True),
            preserve_default=False,
        ),
    ]
