# Generated by Django 3.2.5 on 2021-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_sandwich_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
